### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by enesozturk** [enesozturk/react-native-onesignal-example#1]
![react-native-onesignal-example-screenshot](https://user-images.githubusercontent.com/19428358/81472115-7f332380-91fe-11ea-999b-618e7720ca6d.gif)

**Comment by vikashth1** [comment]
@enesozturk I was looking into your project and it seems helpful but just curious to know that do we have to add Push Notification Extension in iOS as I saw your project not seeing inside that

**Comment by enesozturk** [comment]
Hi @vikashth1 . Thanks for checking out my example. You don't have to add any other package or setup for remote push notifications with OneSignal. The example you see is working on iOS exactly same.

**Comment by vikashth1** [comment]
@enesozturk thank you for prompt response I’m not talking about any other package i have seen the doc from OneSignal and they says to add Push Notifications Extension also i want to creat an page to store push message sent from OneSignal to display inside app can you help me with any example how can I achieve the same.

**Comment by enesozturk** [comment]
Oh I see now. Yes you need to add a simple extension for iOS usage. Not that hard.

For your usage. You want to get remote message but not show notification right?
