### ISSUE TITLE
Do you have any example for Notification page

### ISSUE THREAD

**Issue by vikashth1** [enesozturk/react-native-onesignal-example#2]
Do you have any example for Notification page where I can store the recent notification messages on user device.

**Comment by enesozturk** [comment]
If you want to get all remote notification messages at once, this may not be possible with OneSignal itself. You may need your backend services for your notifications to save them and get all notifs in that page.

**Comment by vikashth1** [comment]
Do you have any examples or references for that how can i do that

**Comment by vikashth1** [comment]
@enesozturk Do you have any examples or references for that how can i do that

**Comment by enesozturk** [comment]
Do you have web service (Rest API etc.) for your project?

**Comment by vikashth1** [comment]
@enesozturk Yes i do have API created using Wordpress and PHP

**Comment by enesozturk** [comment]
Nice. You need to send messages by using your web service. You can check out [this documentation](https://documentation.onesignal.com/reference/create-notification) for anythink you can do with OneSignal REST API.

**Comment by vikashth1** [comment]
@enesozturk Okay it means I need to send message using my web service and need to store same message on database to display inside the app? Correct me if I'm wrong

**Comment by enesozturk** [comment]
Exactly bro 👍🏽

**Comment by vikashth1** [comment]
@enesozturk Thank you so much for all your responses and help.

**Comment by enesozturk** [comment]
Thanks ✋🏽 You can ask anything else if I may help

**Comment by vikashth1** [comment]
@enesozturk Sure, Thank you so much once again

**Comment by vikashth1** [comment]
@enesozturk Hi, Hope you are doing good can you help me with sending image in OneSignal I sent image from OneSignal Panel and it's not showing in my iPhone 11.

**Comment by enesozturk** [comment]
It actually should not that hard too if you are using OneSignal dashboard. I will show what I do for notifs with image asap 👍🏽

**Comment by vikashth1** [comment]
@enesozturk thank you so much will be looking forward for your update

**Comment by vikashth1** [comment]
@enesozturk did you get chance to show me notifs with image

**Comment by enesozturk** [comment]
Hi @vikashth1, Does your notification show up? Or you can not see just image? When I upload new image here. I can see the notification with image actually as you see on the right side on OneSignal.
![Screen Shot 2020-06-18 at 09 28 59](https://user-images.githubusercontent.com/19428358/84985831-25e7d980-b146-11ea-8858-9f7237989197.png)

**Comment by vikashth1** [comment]
@enesozturk Hello, Thank you for your response I can not see just images i received notification but the image which I upload i don't see it

**Comment by enesozturk** [comment]
There must be something different on your setup. Did you do all the steps for [React Native setup](https://documentation.onesignal.com/docs/react-native-sdk-setup) correctly on OneSignal Document? Maybe anything else override OneSignal methods. Did you use any other notification package?

When I send notif to myself like this;
![Screen Shot 2020-06-18 at 10 35 00](https://user-images.githubusercontent.com/19428358/84991938-dc03f100-b14f-11ea-9edd-3a8673b4b6db.png)

I see this;
![Webp net-resizeimage](https://user-images.githubusercontent.com/19428358/84992365-76fccb00-b150-11ea-8103-021b69ff1dd8.jpg)

**Comment by vikashth1** [comment]
@enesozturk Previously I was using Firebase but removed completely from project and yes I did follow the same steps shared by OneSignal but don't know why I am not seeing image

**Comment by enesozturk** [comment]
Did you try notification with new React Native example project (maybe this repo) on Android Simulator or phone? Maybe it help you to understand where the problem is.

**Comment by vikashth1** [comment]
@enesozturk Okay sure I will try and see what's the issue thank you so much for your help

**Comment by vikashth1** [comment]
@enesozturk Not sure but I have checked today and it's started working, However I don't find any option  to send Image from POST Api do you have any idea about that I passing both Variable global_image and ios_attachements

**Comment by enesozturk** [comment]
You need to set different parameters for Android and iOS. You can check out this [source](https://documentation.onesignal.com/docs/rich-media) for more information.

Here is how I use in my API written in Python;
For Android;
```
{
...
"big_picture": image,
...
}
```

For iOS;
```
{
...
"ios_attachments": {"image": image},
...
}
```

**Comment by vikashth1** [comment]
@enesozturk Yes i did the same but the problem is when i use one signal image URL it's showing but when I use my own server Image URL it won't  show up. Even I am using the correct image size and format suggested by OneSignal

**Comment by enesozturk** [comment]
Do you sure that url that shows image is accessible for notification receiver? Could you please run that method with any public image url [like this url from Unsplash](https://images.unsplash.com/photo-1592250924883-42670c0310c0?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=400&ixlib=rb-1.2.1&q=80&w=600).

**Comment by vikashth1** [comment]
@enesozturk Sorry I got the issue with my end sending image URL 
**Make sure your URL is HTTPS. HTTP urls will not work unless you set NSAppTransportSecurity to NSAllowsArbitraryLoads in your Xcode .plist.**

I was sending HTTP image before that's why it was not working but after sending HTTPS it's working now

**Comment by enesozturk** [comment]
Yes it is important point as well. Thanks to remind us. So your problem is solved now?

**Comment by vikashth1** [comment]
@enesozturk Yeah I think I assume need to use image URL with HTTPS only without this it's not working, But it's working for now.

**Comment by enesozturk** [comment]
That is great then 👍🏽

**Comment by vikashth1** [comment]
@enesozturk Yeah Thank You, Much Appreciated all your help 👍🏽

**Comment by enesozturk** [comment]
You are welcome. You solved all the  problems already. I would like to help for issue you get stuck. Have good coding 🙌🏽

**Comment by vikashth1** [comment]
@enesozturk If you don't mind can get any direct way to connect with you so If I had any issue will share with you.

**Comment by vikashth1** [comment]
@enesozturk One more question I have if you don't mind answering that, I see whenever i uninstall and reinstall the app it's register as new device is there any way to update on existing one if already there?

**Comment by enesozturk** [comment]
Hmm, I may not be possible. If you do not uninstall the app, it will update registered user as you see probably. Otherwise, I am not sure of that unfortunately.

**Comment by vikashth1** [comment]
@enesozturk Sorry I'm asking you some bad question please don't mind to receive One-Signal Notification device need to be connected Wi-fi or Mobile Data?

**Comment by enesozturk** [comment]
Thats ok bro. Yes for remote notification device must have connection both Wifi or Mobile data. If you send notification to device that does not have internet. After turning on internet, I must receive the notification. This logic is been handled by phone OS.

**Comment by vikashth1** [comment]
@enesozturk Okay great so I don't have to do anything on our end and also do we have any other option to receive notification without internet?

**Comment by enesozturk** [comment]
Exactly

**Comment by vikashth1** [comment]
@enesozturk Can you help me with some other coding in react native I'm stuck with scrolling inside Tab section I tried adding Flex:1 and flexGrow:1 but it's not scrolling properly if you can give me some idea about this that will be so helpful.
![Simulator Screen Shot - iPhone 11 - 2020-06-28 at 01 48 56](https://user-images.githubusercontent.com/36493549/85931472-39cbd200-b8e2-11ea-84b2-36bfc8dec46d.png)
